# Generated by Django 3.1.4 on 2020-12-31 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=300)),
                ('v1', models.IntegerField()),
                ('c2', models.CharField(max_length=300)),
                ('v2', models.IntegerField()),
                ('c3', models.CharField(max_length=300)),
                ('v3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
