# Generated by Django 3.1.4 on 2020-12-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='c1',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='v1',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='results',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='results',
            name='v2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='v3',
        ),
    ]
